{{ if .Values.prometheus.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-celery-exporter
  labels:
    app: celery-exporter
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: celery-exporter
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/path: /
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: celery-exporter
        args:
        - --listen-address
        - 0.0.0.0:8888
        - --broker-url
        {{ if .Values.rabbitmq.enabled -}}
        - "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:5672/"
        {{- else -}}
        - "amqp://{{ .Values.rabbitmqExternal.username }}:{{ .Values.rabbitmqExternal.password }}@{{ .Values.rabbitmqExternal.host }}:{{ .Values.rabbitmqExternal.port }}/"
        {{- end }}
        - --enable-events
        image: ovalmoney/celery-exporter
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: 50Mi
            cpu: 200m
          requests:
            memory: 25Mi
            cpu: 50m
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- end }}
