apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-hubshell
  labels:
    app: hubshell
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: hubshell
        release: {{ .Release.Name }}
      annotations:
        # Trigger modification of deployment & restart of pods if config changes.
        checksum/config: {{ include (print $.Template.BasePath "/main-configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - name: hubshell
        args:
        - bin/hubshell
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: 80Mi
            cpu: 10m
          limits:
            memory: 240Mi
            cpu: 500m
        volumeMounts:
        - name: {{ .Values.productShortName }}-config
          mountPath: /etc/{{ .Values.productShortName }}/settings/settings.py
          subPath: settings.py
        {{- if .Values.vault.deploy }}
        {{- with (index .Values.vault.server.volumes 1) }}
        - name: {{ .secret.secretName }}
          mountPath: /approle
        {{- end }}
        {{- end }}
      volumes:
      - name: {{ .Values.productShortName }}-config
        configMap:
          name: {{ include "chart.fullname" . }}-{{ .Values.productShortName }}
      {{- if .Values.vault.deploy }}
      {{- with (index .Values.vault.server.volumes 1) }}
      - name: {{ .secret.secretName }}
        secret:
          secretName: {{ .secret.secretName }}
          items:
            - key: roleId
              path: role_id
            - key: secretId
              path: secret_id
      {{- end }}
      {{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
