{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-internal-keys-secret" (include "chart.fullname" .))) }}

{{- $ciliaKey := (randAlphaNum 64) | lower| b64enc | quote }}
{{- $secretKey := (randAlphaNum 64) | lower | b64enc | quote }}
{{- $signKey := (randAlphaNum 64) | lower | b64enc | quote }}

{{- if $secret }}
{{- $ciliaKey = index $secret.data "cilia" }}
{{- $secretKey = index $secret.data "secret" }}
{{- $signKey = index $secret.data "sign" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-internal-keys-secret
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  cilia: {{ $ciliaKey }}
  secret: {{ $secretKey }}
  sign: {{ $signKey }}
