apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-landing
  labels:
    app: landing
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 80
    name: bundled
  - port: 8000
    name: unbundled
  selector:
    app: landing
    release: {{ .Release.Name }}
