apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-sheller
  labels:
    app: sheller
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8086
  selector:
    app: sheller
    release: {{ .Release.Name }}
