apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-traefik
  labels:
    app: traefik
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: traefik
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: traefik
        image: traefik:v1.5
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        # - --logLevel=INFO
        - --accesslog
        # - --accesslog.format=json
        - --api
        - --api.entrypoint=traefik
        - --rest
        - --rest.entrypoint=traefik
        - --defaultentrypoints=http
        - --entrypoints=Name:http Address::80
        - --entrypoints=Name:traefik Address::8080
        ports:
        - containerPort: 80
        - containerPort: 8080
        resources:
          requests:
            memory: 25Mi
            cpu: 10m
          limits:
            memory: 100Mi
            cpu: 2000m
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
