apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-wsproxy
  labels:
    app: wsproxy
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8764
  selector:
    app: wsproxy
    release: {{ .Release.Name }}
