[[http]]
name = "all_backends"
bind-addr = "0.0.0.0:9096"
output = [
    { name="influxdb", location = "http://influxdb:8086/write", type="influxdb" },
]
#{ name="tsfdb", location="http://tsfdb:8080/v1/datapoints", type="influxdb" },

its-all-good-man = true
#max-datapoints-per-request = 100
split-request-per-datapoints = 200
