dependencies:
  - alias: rabbitmq
    condition: rabbitmq.deploy
    repository: https://charts.bitnami.com/bitnami
    name: rabbitmq
    version: 11.2.2
    # RabbitMQ version: 3.11.5
  - alias: mongodb
    condition: mongodb.deploy
    repository: https://charts.bitnami.com/bitnami
    name: mongodb
    version: 13.6.2
    # MongoDB version: 6.0.3
  - alias: victoriametrics
    name: victoria-metrics-cluster
    condition: victoriametrics.deploy
    repository: https://victoriametrics.github.io/helm-charts/
    version: 0.9.37
  - alias: vault
    name: vault
    condition: vault.deploy
    repository: https://helm.releases.hashicorp.com
    version: 0.22.0
    # Vault version: 1.10.3
  - alias: ingress-nginx
    name: ingress-nginx
    condition: ingress-nginx.deploy
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.2.5
